module Mewlix.Packager
( Language(..)
, Action(..)
, ProjectData(..)
, ProjectFlag(..)
, ProjectMode(..)
, Port(..)
, make
, make'
-- Project utils:
, ProjectTransform
, transformProject
-- Defaults:
, defaultMode
, defaultPort
, defaultName
, defaultEntry
-- Lenses:
, projectNameL
, projectDescriptionL
, projectModeL
, projectEntrypointL
, projectPortL
, projectSourceFilesL
, projectAssetsL
, projectSpecialImportsL
, projectFlagsL
) where

import Mewlix.Packager.Data.Types
    ( ProjectData(..)
    , ProjectMode(..)
    , ProjectFlag(..)
    , Port(..)
    , defaultMode
    , defaultPort
    , defaultName
    , defaultEntry
    , ProjectTransform
    , transformProject
    -- Lenses:
    , projectNameL
    , projectDescriptionL
    , projectModeL
    , projectEntrypointL
    , projectPortL
    , projectSourceFilesL
    , projectAssetsL
    , projectSpecialImportsL
    , projectFlagsL
    )
import Mewlix.Packager.Make (Language(..), Action(..), make, make')
