name:         mewlix
version:      1.0.0
author:       kbmackenzie <kelly.a.betty@gmail.com>
github:       kbmackenzie/mewlix
license:      GPL-3.0-only
copyright:    2024 kbmackenzie
description:  |
  A compiler for Mewlix, a cat-themed esoteric programming language that compiles to vanilla Javascript.
  Learn more at <https://github.com/kbmackenzie/mewlix/#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base >= 4.17.2.1 && < 5
- text >= 2.0.2 && < 2.1
- containers >= 0.6.7 && < 0.7
- mtl >= 2.2.2 && < 2.4
- microlens-platform >= 0.4.3.4 && < 0.5
- unordered-containers >= 0.2.19.1 && < 0.3
- megaparsec >= 9.3.1 && < 9.4
- parser-combinators >= 1.3.0 && < 1.4
- bytestring >= 0.11.5.3 && < 0.13
- utf8-string >= 1.0.2 && < 1.1
- filepath >= 1.4.2.2 && < 1.5
- directory >= 1.3.7.1 && < 1.4
- ansi-terminal >= 0.11.5 && < 0.12
- hashable >= 1.4.3.0 && < 1.5
- aeson >= 2.1.2.1 && < 2.2
- conduit >= 1.3.5 && < 1.4
- yaml >= 0.11.11.2 && < 0.12
- wai >= 3.2.4 && < 3.3
- warp >= 3.3.25 && < 3.4
- http-types >= 0.12.4 && < 0.13
- wai-middleware-static >= 0.9.2 && < 1.0
- zip >= 2.0.0 && < 2.1
- open-browser >= 0.2.1.0 && < 0.3
- typed-process >= 0.2.11.1 && < 0.3

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

data-files:
- static/templates/*.zip

library:
  source-dirs: src
  exposed-modules:
  - Mewlix
  - Mewlix.Compiler
  - Mewlix.Logger
  - Mewlix.Packager
  - Mewlix.Parser
  generated-other-modules: Paths_mewlix

executables:
  mewlix:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -static
    dependencies:
    - mewlix
    - optparse-applicative >= 0.17 && < 0.18

tests:
  mewlix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M128m
    dependencies:
    - mewlix
