name:                Meowscript
version:             0.1.0.0
github:              "KBMackenzie/Meowscript"
license:             MIT
author:              "KBMackenzie"
maintainer:          "kelly.a.betty@gmail.com"
copyright:           "2023 KBMackenzie" 

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KBMackenzie/Meowscript/#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- megaparsec >= 9.3.0
- parser-combinators
- mtl
- stopwatch
- bytestring
- filepath
- ansi-terminal
- random
- directory
- monadlist
- network
- clock
- hashable
- transformers
- haskeline
- microlens-platform
- deepseq

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -optc-O3
- -optc-ffast-math
- -funfolding-use-threshold=16
#- -fllvm

data-files:
- std/*.meows

library:
  source-dirs: src

executables:
  Meowscript:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M128m
    dependencies:
    - Meowscript

tests:
  Meowscript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M128m
    dependencies:
    - Meowscript
