name:         mewlix
version:      1.0.0
author:       KBMackenzie <kelly.a.betty@gmail.com>
github:       KBMackenzie/mewlix
license:      MIT
copyright:    2024 KBMackenzie
description:  Please see the README on GitHub at <https://github.com/KBMackenzie/mewlix/#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.1
- containers >= 0.6 && < 0.7
- mtl >= 2.2 && < 2.4
- microlens-platform >= 0.4 && < 0.5
- unordered-containers >= 0.2 && < 0.3
- megaparsec >= 9.3 && < 9.4
- parser-combinators >= 1.3 && < 1.4
- bytestring >= 0.11 && < 0.13
- utf8-string >= 1.0 && < 1.1
- filepath >= 1.4 && < 1.5
- directory >= 1.3 && < 1.4
- ansi-terminal >= 0.11 && < 0.12
- hashable >= 1.4 && < 1.5
- aeson >= 2.1 && < 2.2
- conduit >= 1.3 && < 1.4
- yaml >= 0.11 && < 0.12
- wai >= 3.2 && < 3.3
- warp >= 3.3 && < 3.4
- zip >= 2.0 && < 2.1
- scotty >= 0.12 && < 0.13
- wai-middleware-static >= 0.9 && < 1.0
- optparse-applicative >= 0.17 && < 0.18
- open-browser >= 0.2 && < 0.3

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

data-files:
- templates/js/*.zip

library:
  source-dirs: src

executables:
  mewlix:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    dependencies:
    - mewlix

tests:
  mewlix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M128m
    dependencies:
    - mewlix
