name:                Mewlix
version:             0.1.0.0
github:              "KBMackenzie/Mewlix"
license:             MIT
author:              "KBMackenzie"
maintainer:          "kelly.a.betty@gmail.com"
copyright:           "2023 KBMackenzie" 

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KBMackenzie/Mewlix/#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.1
- containers >= 0.6 && < 0.7
- mtl >= 2.2 && < 2.4
- microlens-platform >= 0.4 && < 0.5
- unordered-containers >= 0.2 && < 0.3
- megaparsec >= 9.3 && < 9.4
- parser-combinators >= 1.3 && < 1.4
- bytestring >= 0.11 && < 0.13
- utf8-string >= 1.0 && < 1.1
- filepath >= 1.4 && < 1.5
- directory >= 1.3 && < 1.4
- ansi-terminal >= 1.0 && < 1.1
- haskeline >= 0.8 && < 0.9
- random >= 1.2 && < 1.3
- hashable >= 1.4 && < 1.5
- aeson >= 2.2 && < 2.3
- conduit >= 1.3 && < 1.4
- yaml >= 0.11 && < 0.12
- cmdargs >= 0.10 && < 0.11

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -optc-O3
- -optc-ffast-math
- -funfolding-use-threshold=16

#data-files:
#- std/*.meows

library:
  source-dirs: src

executables:
  Mewlix:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M128m
    dependencies:
    - Mewlix

tests:
  Mewlix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M128m
    dependencies:
    - Mewlix
