#system-ghc: true
resolver: ghc-9.4.7

extra-deps:
- text-2.0.2
- vector-0.13.1.0
- vector-stream-0.1.0.1
- hashable-1.4.2.0
- primitive-0.8.0.0
- unordered-containers-0.2.19.1
- transformers-compat-0.7.2
- microlens-0.4.13.1
- microlens-ghc-0.4.14.1
- microlens-platform-0.4.3.3
- microlens-mtl-0.2.0.3
- microlens-th-0.4.3.13
- th-abstraction-0.5.0.0
- megaparsec-9.3.0
- parser-combinators-1.3.0
- case-insensitive-1.2.1.0
- scientific-0.3.7.0
- integer-logarithms-1.0.3.1
- utf8-string-1.0.2
- ansi-terminal-1.0
- ansi-terminal-types-0.11.5
- colour-2.3.6
- random-1.2.1.1
- splitmix-0.1.0.4
# Conduit
- conduit-1.3.5
- resourcet-1.3.0
- mono-traversable-1.0.15.3
- unliftio-core-0.2.1.0
- split-0.2.5
- vector-algorithms-0.9.0.1
- bitvec-1.1.5.0
# Aeson
- aeson-2.2.1.0
- OneTuple-0.4.1.1
- QuickCheck-2.14.3
- data-fix-0.3.2
- dlist-1.0
- generically-0.1.1
- indexed-traversable-0.1.3
- integer-conversion-0.1.0.1
- network-uri-2.6.4.2
- semialign-1.3
- strict-0.5
- tagged-0.8.8
- text-iso8601-0.1
- text-short-0.1.5
- these-1.2
- time-compat-1.9.6.1
- uuid-types-1.0.5.1
- witherable-0.4.2
- base-orphans-0.9.1
- foldable1-classes-compat-0.1
- th-compat-0.1.4
- indexed-traversable-instances-0.1.1.2
- semigroupoids-6.0.0.1
- assoc-1.1
- bifunctors-5.6.1
- comonad-5.0.8
- contravariant-1.5.5
- distributive-0.6.2.1
- StateVar-1.2.2
# YAML
- yaml-0.11.11.2
- attoparsec-0.14.4
- libyaml-0.1.2
# wai
- wai-3.2.4
- network-3.1.4.0
- http-types-0.12.4
- vault-0.3.1.5
# warp
- warp-3.3.31
- auto-update-0.1.6
- bsb-http-chunked-0.0.0.4
- crypton-x509-1.7.6
- http-date-0.0.11
- http2-5.0.1
- iproute-1.7.12
- recv-0.1.0
- simple-sendfile-0.2.32
- streaming-commons-0.2.2.6
- time-manager-0.0.1
- unliftio-0.2.25.0
- word8-0.1.3
- asn1-encoding-0.9.6
- asn1-parse-0.9.5
- asn1-types-0.3.4
- crypton-0.34
- hourglass-0.2.12
- memory-0.18.0
- pem-0.2.4
- async-2.2.5
- network-byte-order-0.1.7
- network-control-0.0.2
- unix-time-0.4.12
- appar-0.1.8
- byteorder-1.0.4
- zlib-0.7.0.0
- safe-exceptions-0.1.7.4
- basement-0.0.16
- psqueues-0.2.8.0
- old-time-1.1.0.4
- old-locale-1.0.0.7
# zip
- zip-2.0.0
- bzlib-conduit-0.3.0.2
- cereal-0.5.8.3
- conduit-extra-1.3.6
- conduit-zstd-0.0.2.0
- digest-0.0.2.1
- monad-control-1.0.3.1
- transformers-base-0.4.6
- bindings-DSL-1.0.25
- data-default-class-0.1.2.0
- typed-process-0.2.11.1
- zstd-0.1.3.0
# scotty
- scotty-0.21
- blaze-builder-0.4.2.3
- regex-compat-0.95.2.1
- cookie-0.4.6
- wai-extra-3.1.14
- regex-base-0.94.0.2
- regex-posix-0.96.0.1
- HUnit-1.6.2.0
- base64-bytestring-1.2.1.0
- call-stack-0.4.0
- fast-logger-3.2.2
- wai-logger-2.4.0
- easy-file-0.2.5
- unix-compat-0.7.1
- cabal-doctest-1.0.9
# wai middleware
- wai-middleware-static-0.9.2
- base16-bytestring-1.0.2.0
- cryptohash-sha1-0.11.101.0
- expiring-cache-map-0.0.6.1
- mime-types-0.1.2.0
- semigroups-0.20
