#system-ghc: true
resolver: ghc-9.2.8

extra-deps:
- text-2.0.2
- hashable-1.4.2.0
- vector-0.13.0.0
- data-array-byte-0.1.0.1
- primitive-0.8.0.0
- vector-stream-0.1.0.0
- unordered-containers-0.2.19.1
- transformers-compat-0.7.2
- microlens-0.4.13.1
- microlens-ghc-0.4.14.1
- microlens-platform-0.4.3.3
- microlens-mtl-0.2.0.3
- microlens-th-0.4.3.13
- th-abstraction-0.5.0.0
- monadlist-0.0.2
- megaparsec-9.3.0
- parser-combinators-1.3.0
- case-insensitive-1.2.1.0
- scientific-0.3.7.0
#- hashable-1.4.2.0
- integer-logarithms-1.0.3.1
- utf8-string-1.0.2
#- primitive-0.8.0.0
#- base-orphans-0.9.0
#- data-array-byte-0.1.0.1
#- megaparsec-9.3.0
#- stopwatch-0.1.0.6
#- clock-0.8.3
#- ansi-terminal-0.11.4
#- colour-2.3.6
#- filepath-1.4.100.3
#- bytestring-0.11.4.0
#- binary-0.8.9.1
#- text-2.0.2
#- random-1.2.1.1
#- splitmix-0.1.0.4
#- directory-1.3.8.1
#- unix-2.8.1.1
#- network-3.1.2.9
#- haskeline-0.8.2.1
#- process-1.6.17.0
#- microlens-platform-0.4.3.3
#- microlens-0.4.13.1
#- microlens-ghc-0.4.14.1
#- microlens-mtl-0.2.0.3
#- microlens-th-0.4.3.13
#- unordered-containers-0.2.19.1
#- vector-0.13.0.0
#- transformers-compat-0.7.2
#- th-abstraction-0.5.0.0
#- vector-stream-0.1.0.0
