#system-ghc: true
resolver: ghc-9.4.7

extra-deps:
- text-2.0.2
- vector-0.13.1.0
- vector-stream-0.1.0.1
- hashable-1.4.2.0
- primitive-0.8.0.0
- unordered-containers-0.2.19.1
- transformers-compat-0.7.2
- microlens-0.4.13.1
- microlens-ghc-0.4.14.1
- microlens-platform-0.4.3.3
- microlens-mtl-0.2.0.3
- microlens-th-0.4.3.13
- th-abstraction-0.5.0.0
- megaparsec-9.3.0
- parser-combinators-1.3.0
- case-insensitive-1.2.1.0
- scientific-0.3.7.0
- integer-logarithms-1.0.3.1
- utf8-string-1.0.2
- ansi-terminal-1.0
- ansi-terminal-types-0.11.5
- colour-2.3.6
- random-1.2.1.1
- splitmix-0.1.0.4
# Conduit
- conduit-1.3.5
- resourcet-1.3.0
- mono-traversable-1.0.15.3
- unliftio-core-0.2.1.0
- split-0.2.5
- vector-algorithms-0.9.0.1
- bitvec-1.1.5.0
# Aeson
- aeson-2.2.1.0
- OneTuple-0.4.1.1
- QuickCheck-2.14.3
- data-fix-0.3.2
- dlist-1.0
- generically-0.1.1
- indexed-traversable-0.1.3
- integer-conversion-0.1.0.1
- network-uri-2.6.4.2
- semialign-1.3
- strict-0.5
- tagged-0.8.8
- text-iso8601-0.1
- text-short-0.1.5
- these-1.2
- time-compat-1.9.6.1
- uuid-types-1.0.5.1
- witherable-0.4.2
- base-orphans-0.9.1
- foldable1-classes-compat-0.1
- th-compat-0.1.4
- indexed-traversable-instances-0.1.1.2
- semigroupoids-6.0.0.1
- assoc-1.1
- bifunctors-5.6.1
- comonad-5.0.8
- contravariant-1.5.5
- distributive-0.6.2.1
- StateVar-1.2.2
# YAML
- yaml-0.11.11.2
- attoparsec-0.14.4
- libyaml-0.1.2
